# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

exclude: '^tests/cosmetic/'

repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.0
    hooks:
    -   id: setup-cfg-fmt
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
      -  id: mypy
         args:
         -   --disallow-incomplete-defs
         -   --ignore-missing-imports
         -   --disable-error-code
         -   attr-defined
-   repo: https://github.com/hakancelik96/unimport
    rev: 0.9.4
    hooks:
      - id: unimport
        args:
        -   --remove
        -   --ignore-init
-   repo: https://github.com/executablebooks/mdformat/
    rev: 0.7.13
    hooks:
    -   id: mdformat
        additional_dependencies:
        - mdformat_tables
        - mdformat-black
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
